<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro" name="myrobot">
  <xacro:property name="base_length" value="0.8" />
  <xacro:property name="base_width" value="0.5" />
  <xacro:property name="base_height" value="0.9" />
  <xacro:property name="radius1" value="0.2" />
  <xacro:property name="laser_width" value="0.1" />
  <xacro:property name="wheel_radius" value="0.2" />
  <xacro:property name="wheel_thickness" value="0.1" />
  <xacro:property name="wheel_offset" value="0.1" />
  <xacro:property name="arm1_length" value="0.9" />
  <xacro:property name="arm1_width" value="0.05" />
  <xacro:property name="arm1_height" value="0.1" />

  <xacro:macro name="inertial_sphere" params="mass radius *origin">
    <inertial>
      <xacro:insert_block name="origin" />
      <mass value="${mass}" />
      <inertia ixx="${(2/5) * mass * (radius*radius)}" ixy="0.0" ixz="0.0"
        iyy="${(2/5) * mass * (radius*radius)}" iyz="0.0"
        izz="${(2/5) * mass * (radius*radius)}" />
    </inertial>
  </xacro:macro>


  <xacro:macro name="inertial_box" params="mass x y z *origin">
    <inertial>
      <xacro:insert_block name="origin" />
      <mass value="${mass}" />
      <inertia ixx="${(1/12) * mass * (y*y+z*z)}" ixy="0.0" ixz="0.0"
        iyy="${(1/12) * mass * (x*x+z*z)}" iyz="0.0"
        izz="${(1/12) * mass * (x*x+y*y)}" />
    </inertial>
  </xacro:macro>


  <xacro:macro name="inertial_cylinder" params="mass length radius *origin">
    <inertial>
      <xacro:insert_block name="origin" />
      <mass value="${mass}" />
      <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
        iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
        izz="${(1/2) * mass * (radius*radius)}" />
    </inertial>
  </xacro:macro>

  <material name="Orange">
    <color rgba="1 0.5 0 1" />
  </material>
  <material name="yellow">
    <color rgba="1 1 0 1" />
  </material>
  <material name="black">
    <color rgba="0 0 0 1" />
  </material>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
      <material name="Orange" />
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </collision>
    <!-- <inertial> -->
    <!--   <origin xyz="0 0 0" rpy="0 0 0" /> -->
    <!--   <mass value="0.1" /> -->
    <!--   <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" /> -->
    <!-- </inertial> -->
    <xacro:inertial_box mass="0.3" x="${base_length}" y="${base_width}" z="${base_height}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_box>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Orange</material>
  </gazebo>

  <link name="laser_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder length="${laser_width}" radius="${radius1}" />
      </geometry>
      <material name="yellow" />
    </visual>
  </link>

  <gazebo reference="laser_link">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <joint name="base_laser_joint" type="fixed">
    <origin xyz="0 0 ${base_height + laser_width/2}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="laser_link" />
  </joint>

  <link name="left_wheel">
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
      </geometry>
      <material name="black" />
    </visual>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <origin xyz="-${base_length/2-wheel_offset} -${base_width/2+wheel_thickness/2} 0"
      rpy="${pi/2} 0 0" />
    <parent link="base_link" />
    <child link="left_wheel" />
    <axis xyz="0 0 1" />
  </joint>

  <link name="right_wheel">
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
      </geometry>
      <material name="black" />
    </visual>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <origin xyz="-${base_length/2-wheel_offset} ${base_width/2+wheel_thickness/2} 0"
      rpy="${pi/2} 0 0" />
    <parent link="base_link" />
    <child link="right_wheel" />
    <axis xyz="0 0 1" />
  </joint>

  <link name="arm1">
    <visual>
      <origin xyz="-${base_length/2} 0 0" />
      <geometry>
        <box size="${arm1_length} ${arm1_width} ${arm1_height}" />
      </geometry>
    </visual>
  </link>
  <joint name="arm1_joint" type="revolute">
    <origin xyz="-${base_length/2} 0 ${base_height}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="arm1" />
    <axis xyz="0 1 0" />
    <limit lower="${-pi/6}" upper="${pi/6}" effort="100" velocity="100" />
  </joint>

  <link name="rear_wheel">
    <visual>
      <geometry>
        <sphere radius="${wheel_radius}" />
      </geometry>
      <material name="black" />
    </visual>
  </link>

  <joint name="rear_wheel_joint" type="fixed">
    <origin xyz="${base_length/2-wheel_offset} 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="rear_wheel"/>
  </joint>

</robot>
